name: Cron Update Next

on:
  # Allow manual runs
  workflow_dispatch:
  # Run every 10 minutes https://crontab.guru/every-10-minutes
  schedule:
    - cron: '*/10 * * * *'

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      contents: write
      pull-requests: write
      issues: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        # 0 means fetch all commits so we can commit and push in the script below
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Enable corepack
        run: corepack enable pnpm
      - name: Create Pull Request
        uses: actions/github-script@v7
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # See https://github.com/actions/github-script#run-a-separate-file-with-an-async-function
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const script = require('./utils/update-next.js')
            await script({ github, context, tag: 'canary' })
