name: Prebuild Next.js Example

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:

jobs:
  clone-build-deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN_PULL_REQUESTS || secrets.GITHUB_TOKEN }}

      - uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'npm'
          cache-dependency-path: './examples/nextjs/package-lock.json'

      - run: |
          node --version
          npm --version

      - run: |
          npm install -g vercel@latest
          vc --version

      - working-directory: ./examples/nextjs
        run: |
          npm ci
        env:
          NPM_CONFIG_LOGLEVEL: http

      - working-directory: ./examples/nextjs
        run: |
          vc build --debug --token $VERCEL_TOKEN --yes --prod
        env:
          VERCEL_PROJECT_ID: prj_qav3SWw0ZQDfehj7w47xPaBESx8P
          VERCEL_TOKEN: ${{ secrets.NOW_EXAMPLES_VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.NOW_EXAMPLES_VERCEL_ORG_ID }}

      - working-directory: ./examples/nextjs
        run: |
          vc deploy --debug --token $VERCEL_TOKEN --yes --prod --prebuilt --archive=tgz
        env:
          VERCEL_PROJECT_ID: prj_qav3SWw0ZQDfehj7w47xPaBESx8P
          VERCEL_TOKEN: ${{ secrets.NOW_EXAMPLES_VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.NOW_EXAMPLES_VERCEL_ORG_ID }}
